name: poze

description: "A modern macOS process manager built with Flutter."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  macos_ui: ^2.0.0
  process_run: ^0.14.0
  provider: ^6.1.1
  shared_preferences: ^2.5.3
  tray_manager: ^0.2.2
  window_manager: ^0.4.3
  local_notifier: ^0.1.6
  launch_at_startup: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/app_icon.png
